version: '2.3'
services:

  connect:
    hostname: connect
    image: rstudio/rstudio-connect:${RSC_VERSION}
    scale: 2
    ports:
      - 3939
    privileged: true
    environment:
      - RSC_LICENSE
      - RSC_HASTE_ENABLED=true
    platform: linux/amd64
    # if you need to customize Connect config until we have env vars
    # volumes:
    #  - ../../tmp.gcfg:/etc/rstudio-connect/rstudio-connect.gcfg
