---
title: "`r tag`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: custom.css
    includes:
      in_header: "custom_lazyload.html"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(htmltools)
```

```{r subpages, include = FALSE}
out <- mapply(function(app, iter){
  subpage_env <- new.env()
  assign("subpage_link", app$url, subpage_env)
  assign("subpage_title", app$title, subpage_env)
  assign("subpage_number", iter, subpage_env)
  assign("subpage_group", app$content_group, subpage_env)
  
  knitr::knit_child("tag_page_iframe_page.Rmd", envir = subpage_env)
}, app = apps, iter = as.list(seq_along(apps)), SIMPLIFY = FALSE)

```
`r paste(knitr::knit_child(text = out), collapse = '')`

```{r results='asis'}
# to find the event: https://getbootstrap.com/docs/4.0/components/navs/
htmltools::tags$script(
"
$.lazyLoadXT.selector = 'iframe[data-src]'
$.lazyLoadXT.updateEvent = $.lazyLoadXT.updateEvent + ' shown.bs.tab'
"
)
```
